/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CoreIdempotencyKey {
  actor_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key: string;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
}

export interface CoreOutboxEvent {
  aggregate_id: string;
  aggregate_type: string;
  event_type: string;
  id: Generated<string>;
  occurred_at: Generated<Timestamp>;
  payload: Json;
  published_at: Timestamp | null;
  schema_version: Generated<number>;
  seq: Generated<Int8>;
}

export interface CoreTombstone {
  deleted_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  sync_seq: Generated<Int8>;
}

export interface DB {
  "core.idempotency_key": CoreIdempotencyKey;
  "core.outbox_event": CoreOutboxEvent;
  "core.tombstone": CoreTombstone;
}
