/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditPiiAccessLog {
  action: string;
  actor_id: string;
  at: Generated<Timestamp>;
  entity_field: string;
  reason: string | null;
  request_context: Generated<Json>;
  seq: Generated<Int8>;
  subject_contact_id: string | null;
}

export interface CoreContact {
  created_at: Generated<Timestamp>;
  dek_id: string | null;
  display_name: string | null;
  id: Generated<string>;
  idp_subject_id: string | null;
  lifecycle_state: Generated<string>;
  locale: Generated<string>;
  merged_into: string | null;
  processing_restricted: Generated<boolean>;
  sync_seq: Generated<Int8>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CoreContactChannel {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_preferred: Generated<boolean>;
  kind: string;
  value_normalised: string;
  verification_state: Generated<string>;
}

export interface CoreContactMerge {
  absorbed_id: string;
  id: Generated<string>;
  merged_at: Generated<Timestamp>;
  merged_by: string | null;
  pre_merge_snapshot: Json;
  surviving_id: string;
  unmerged_at: Timestamp | null;
}

export interface CoreContactRelationship {
  from_contact_id: string;
  id: Generated<string>;
  kind: string;
  to_contact_id: string;
  validity: Generated<string>;
}

export interface CoreContactRole {
  activated_at: Generated<Timestamp>;
  contact_id: string;
  ended_at: Timestamp | null;
  id: Generated<string>;
  role: string;
  state: Generated<string>;
}

export interface CoreContactSensitive {
  contact_id: string;
  iban_enc: Buffer | null;
  national_id_enc: Buffer | null;
  updated_at: Generated<Timestamp>;
}

export interface CoreFieldPrecedenceRule {
  entity_type: string;
  field_name: string;
  method_ranking: Json;
}

export interface CoreFieldProvenance {
  candidate: Json | null;
  collected_at: Timestamp;
  confidence: Numeric | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  field_name: string;
  id: Generated<string>;
  method: string;
  source_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CoreIdempotencyKey {
  actor_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key: string;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
}

export interface CoreIngestRecord {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  id: Generated<string>;
  idempotency_key: string;
  kind: string;
  outcome: string | null;
  payload: Json | null;
  problem_code: string | null;
  property_id: string | null;
  quarantine_reason: string | null;
  run_id: string;
  source_id: string;
}

export interface CoreIngestRun {
  finished_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string;
  request_hash: string;
  source_id: string;
  started_at: Generated<Timestamp>;
  stats: Generated<Json>;
  status: Generated<string>;
}

export interface CoreListing {
  channel: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  description: string | null;
  id: Generated<string>;
  price: Numeric | null;
  property_id: string;
  source_url: string | null;
  state: Generated<string>;
  state_entered_at: Generated<Timestamp>;
  sync_seq: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface CoreListingChange {
  changed_at: Generated<Timestamp>;
  field: string;
  id: Generated<string>;
  listing_id: string;
  new_value: Json | null;
  old_value: Json | null;
  provenance_id: string | null;
}

export interface CoreMediaAsset {
  caption: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: Generated<string>;
  listing_id: string | null;
  position: Generated<number>;
  property_id: string;
  rights_status: Generated<string>;
  storage_key: string | null;
  url: string | null;
}

export interface CoreOrganisation {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  name: string;
  registration_number: string | null;
}

export interface CoreOrgMembership {
  contact_id: string;
  id: Generated<string>;
  organisation_id: string;
  role_in_org: string;
  validity: Generated<string>;
}

export interface CoreOutboxEvent {
  aggregate_id: string;
  aggregate_type: string;
  event_type: string;
  id: Generated<string>;
  occurred_at: Generated<Timestamp>;
  payload: Json;
  published_at: Timestamp | null;
  schema_version: Generated<number>;
  seq: Generated<Int8>;
}

export interface CorePortfolioEntry {
  added_at: Generated<Timestamp>;
  contact_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<string>;
  last_estimated_at: Timestamp | null;
  last_value_estimate: Numeric | null;
  monthly_expenses: Numeric;
  monthly_rental_income: Numeric;
  property_id: string;
  purchase_price: Numeric;
  status: Generated<string>;
  sync_seq: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface CoreProperty {
  address_normalised: Json;
  bedrooms: number | null;
  canonical_key: string;
  created_at: Generated<Timestamp>;
  epc_rating: string | null;
  features: Generated<Json>;
  floor_area_sqm: Numeric | null;
  free_attributes: Generated<Json>;
  geo_point: string | null;
  id: Generated<string>;
  kind: string | null;
  merged_into: string | null;
  occupancy: string | null;
  sync_seq: Generated<Int8>;
  tenure: string | null;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CorePropertyDocument {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  issued_at: Timestamp | null;
  kind: string;
  property_id: string;
  storage_key: string;
  verification_state: Generated<string>;
}

export interface CorePropertyMerge {
  absorbed_id: string;
  id: Generated<string>;
  merged_at: Generated<Timestamp>;
  merged_by: string | null;
  pre_merge_snapshot: Json;
  surviving_id: string;
  unmerged_at: Timestamp | null;
}

export interface CorePropertyParty {
  contact_id: string;
  id: Generated<string>;
  ownership_share: Numeric | null;
  property_id: string;
  role: string;
  validity: Generated<string>;
}

export interface CoreQuarantineItem {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ingest_record_id: string;
  reason: string;
  resolution: Json | null;
  reviewed_by: string | null;
  state: Generated<string>;
}

export interface CoreSource {
  created_at: Generated<Timestamp>;
  default_lawful_basis: Generated<string>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  kind: string;
  name: string;
}

export interface CoreSuppressionEntry {
  created_at: Generated<Timestamp>;
  dsr_id: string | null;
  id: Generated<string>;
  kind: string;
  reason: Generated<string>;
  value_hmac: string;
}

export interface CoreTombstone {
  deleted_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  sync_seq: Generated<Int8>;
}

export interface DB {
  "audit.pii_access_log": AuditPiiAccessLog;
  "core.contact": CoreContact;
  "core.contact_channel": CoreContactChannel;
  "core.contact_merge": CoreContactMerge;
  "core.contact_relationship": CoreContactRelationship;
  "core.contact_role": CoreContactRole;
  "core.contact_sensitive": CoreContactSensitive;
  "core.field_precedence_rule": CoreFieldPrecedenceRule;
  "core.field_provenance": CoreFieldProvenance;
  "core.idempotency_key": CoreIdempotencyKey;
  "core.ingest_record": CoreIngestRecord;
  "core.ingest_run": CoreIngestRun;
  "core.listing": CoreListing;
  "core.listing_change": CoreListingChange;
  "core.media_asset": CoreMediaAsset;
  "core.org_membership": CoreOrgMembership;
  "core.organisation": CoreOrganisation;
  "core.outbox_event": CoreOutboxEvent;
  "core.portfolio_entry": CorePortfolioEntry;
  "core.property": CoreProperty;
  "core.property_document": CorePropertyDocument;
  "core.property_merge": CorePropertyMerge;
  "core.property_party": CorePropertyParty;
  "core.quarantine_item": CoreQuarantineItem;
  "core.source": CoreSource;
  "core.suppression_entry": CoreSuppressionEntry;
  "core.tombstone": CoreTombstone;
}
